# Site
title:              Dalimunthe Blog
bio:                'Anything I Want and I Care.'
description:        "i do some html, php and python language, sometimes make some maps sometimes i develop new things."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                http://dalimunthe.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   rssyid

# Social
# if you don't have any of social below, comment the line.
google:
  plus:+RasyidAhyarDalimunthe
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email: rasyid.dalimunthe@gmail.com
twitter:            rssyid
facebook:           rasyid.ahyar
github:             dalimunthe
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:          rssyid
#xing:              username
instagram:          rssyid
lastfm:            earbutt
#tumblr:            username
#pinterest:         username
#foursquare:        username
steam:              asnaeb_one
#dribbble:          username
youtube:           rotttenone
soundcloud:        rasyid-ahyar
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
